.github/workflows/deploy-preview.yaml

This will probably need to be merged before taking effect

Fix preview link

---

.github/workflows/update-cookbook-gallery.yaml

change repo-token to github_token

---

.github/workflows/update-cookbook-gallery.yaml

Following instructions here: https://michaelheap.com/ultimate-guide-github-actions-authentication/

try different token method

---

site/cookbook_gallery.txt

[The cookbook](https://cookbooks.projectpythia.org/cesm-lens-aws-cookbook/README.html)

Update gallery with CESM LENS cookbook

---

.github/workflows/collect-user-submission.py

Without the extra "Did you check" locally this returns an empty string, now locally it is correct.

make right string more specific

---

.github/workflows/update-cookbook-gallery.yaml

Related to this message. 
`
Warning: Unexpected input(s) 'repository', valid inputs are ['token', 'path', 'add-paths', 'commit-message', 'committer', 'author', 'signoff', 'branch', 'delete-branch', 'branch-suffix', 'base', 'push-to-fork', 'title', 'body', 'labels', 'assignees', 'reviewers', 'team-reviewers', 'milestone', 'draft']
`

repository unexpected input

---

site/cookbook_gallery.txt

Removing some cookbooks from the gallery

---

.github/CODEOWNERS
.github/workflows/update-cookbook-gallery.yaml
README.md
site/_extensions/cookbook_gallery_generator.py

Remove all references to deprecated ProjectPythiaCookbooks org, and rename this repo from `projectpythiacookbooks.github.io` to `cookbook-gallery`

Finish migration and renaming of this repo

---

site/radar-cookbook/index.md

This PR adds a hard-coded redirect notice that should show up at https://cookbooks.projectpythia.org/radar-cookbook/

Add redirect notice for Radar Cookbook

---

site/_extensions/gallery_generator.py

trivial change to force rebuild

---

environment.yml
site/_extensions/gallery_generator.py

use citation and gallery_info files if can

---

site/cookbook_gallery.txt

Add ERA5_interactive-cookbook to gallery

---

site/_extensions/gallery_generator.py

Addresses #162 
This PR fetches the GitHub ID of each cookbook repo and uses them to construct links to the latest Zenodo DOI and associated badge. The badge is displayed on the gallery card next to the binder link.
Also some light refactoring of the gallery generation code.

Display DOI badges on gallery

---

site/conf.py

Adds blog link in navbar, see https://github.com/ProjectPythia/projectpythia.github.io/pull/347

Update conf.py with blog link

---

site/cookbook_gallery.txt

Closes #181 
Add unstructured-grid-viz-cookbook

Update cookbook_gallery.txt - Add unstructured-grid-viz-cookbook

---

site/_templates/footer-menu.html

Need to add metrics to the footer of Cookbooks gallery and Foundations book.
Related to https://github.com/ProjectPythia/projectpythia.github.io/issues/319

Update footer-menu.html to have metrics

---

site/_extensions/gallery_generator.py

Closes #153 
This PR changes how author names are displayed on gallery cards, putting them in more readable order [given names] [family name]

Reverse name order when building author list

---

.pre-commit-config.yaml

Was commented out, but go ahead and remove to be consistent.

Remove prettier

---

site/cookbook_gallery.txt

This PR adds the paleoPCA-cookbook to the gallery. This was a 2024 hackathon contribution and had gone through a thorough review

Add paleoPCA-cookbook

---

site/cookbook_gallery.txt

This cookbook covers an introduction to the [Hierarchical Equal Area isoLatitude Pixelation (HEALPix)](https://healpix.sourceforge.io/) of the Earth and utilization of [easy.gems](https://easy.gems.dkrz.de/index.html#) and [UXarray](https://uxarray.readthedocs.io/) to run data analysis and visualization functionality on HEALPix data sets.
Driven by [The 2025 World Climate Research Programme (WCRP) Digital Earths Global KM-scale Hackathon](https://www.wcrp-esmo.org/activities/wcrp-global-km-scale-hackathon-2025) taking place 12-16 May, a need for exploring HEALPix and documenting HEALPix-based workflows that utilize community resources such as the easy.gems documentation and UXarray software tool has emerged. Project Pythia Cookbooks are a great medium to publish such documentation in an …

Add HEALPix Cookbook
